[loglugger_server]
server-1 ansible_host=192.168.10.10

[loglugger_client]
client-1 ansible_host=192.168.10.21
client-2 ansible_host=192.168.10.22

[all:vars]
ansible_user=ubuntu
ansible_become=true

# Optional examples:
# loglugger_server_listen_addr=:28443
# loglugger_client_server_scheme=https
# loglugger_client_server_port=28443
# loglugger_server_ydb_endpoint=grpcs://ydb.example.internal:2135
# loglugger_server_ydb_database=/prod
# loglugger_server_ydb_table=ydblogs
