---
loglugger_prefix: /opt/ydb/loglugger
loglugger_local_bin_dir: ./bin
loglugger_client_id: "{{ inventory_hostname }}"
loglugger_client_server_urls: []
loglugger_client_server_group: "loglugger_server"
loglugger_client_server_scheme: "https"
loglugger_client_server_port: 27312
loglugger_client_service_mask: ""
loglugger_client_journal_recovery: true
loglugger_client_batch_size: 50000
loglugger_client_batch_timeout: "5s"
loglugger_client_http_timeout: "30s"
loglugger_client_retry_delay: "1s"

loglugger_cert_dir: /opt/ydb/certs
loglugger_client_tls_ca_file: "{{ loglugger_cert_dir }}/ca.crt"
loglugger_client_tls_cert_file: "{{ loglugger_cert_dir }}/node.crt"
loglugger_client_tls_key_file: "{{ loglugger_cert_dir }}/node.key"
